### ISSUE TITLE
github.com/typesense/typesense-go/v2/go.mod does not exist

### ISSUE THREAD

**Issue by dahvlhldle** [typesense/typesense-go#162]
github.com/typesense/typesense-go/v2/go.mod does not exist

**Comment by mynlexi** [comment]
same here cant upgrade

**Comment by kishorenc** [comment]
Some `pkg.go.dev` is not picking up the latest release: https://github.com/typesense/typesense-go/releases/tag/v2.0.0

**Comment by leetm4n** [comment]
by go module standard, because you bumped to v2 it should be under repo/v2/

**Comment by leetm4n** [comment]
or you could do what e.g. labstack/echo did: https://github.com/labstack/echo/blob/master/go.mod

they just have v2 in the root gomod, but sadly you cannot tag v2 without you updating to v2 gomod

**Comment by cysp** [comment]
Looking at the changes in v2, are they actually a semver-major change? The phrasing in the upgrade notes sounds like the added generic types are an optional feature rather than a source-breaking one. It seems like the simplest solution would be to release that as an update in the v1 release line rather than bumping the major version, given all of this rigmarole with changing import paths.
Would that be an option?

**Comment by kishorenc** [comment]
Given that there were no breaking changes, I've published `v1.1.0` instead and deleted the earlier v2 release.
